# Makes it required to have super user level permissions in order to execute
 #this build.
sudo: required

# make sure that Travis.ci realizes we need docker pre-installed:
services:
 #travis.ci is going to automatically install docker on our running container. 
 - docker

# create a series of commands/steps that are going to be ran before running our
 #tests or pushing to production. 
before_install:
 #force a build from the Dockerfile.dev file while looking in "." (current dir).
 - docker build -t charlesderek/docker-react -f Dockerfile.dev .
  #-t:
  #charlesderek: Our username in Docker
  #docker-react: The build name we intend to use (best practice to use repo name).

# script: Contains all the specific commands needed to be executed to actually
 #run our test suite.
script:
 #NOTE: any other command besides '0' will be assumed as failure.
 - docker run charlesderek/docker-react npm run test -- --coverage
 # [ -- -- coverage ]: executes the test the destroys the image when results are
  #finished, and returns the results of the test execution.
